# Generated by Django 3.1.3 on 2021-09-03 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimelineEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mood', models.CharField(max_length=100)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', related_query_name='timeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Timeline Entry',
                'verbose_name_plural': 'User Timeline Entries',
                'db_table': 'user_timeline_entry',
            },
        ),
        migrations.CreateModel(
            name='UserTimelineEntryCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeline_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_timeline_entry_conditions', related_query_name='user_timeline_entry_conditions', to='users.usertimelineentry')),
            ],
            options={
                'verbose_name': 'User Timeline Entry Condition',
                'verbose_name_plural': 'User Timeline Entry Conditions',
                'db_table': 'user_timeline_entry_condition',
            },
        ),
    ]
