# Generated by Django 3.1.3 on 2021-09-06 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Doctor',
                'verbose_name_plural': 'Patients Doctors',
                'db_table': 'patient_doctor',
            },
        ),
        migrations.AddField(
            model_name='usertimelineentry',
            name='patient_note',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserTimelineEntryCondition',
        ),
    ]
